### ISSUE TITLE
 Issue- forrtl: severe (9): permission to access file denied, unit 11, file C:\Program Files\ANSYS Inc\v211\aqwa\bin\winx64\PMESSAGE.TMP

### ISSUE THREAD

**Issue by ashwing1407** [yang7857854/F2A#2]
Hello Yang, I am trying to run F2A and this error appears can you help me? I am using Ansys 2021 R1.

![Screenshot 2022-10-20 113930](https://user-images.githubusercontent.com/85031933/196869474-a0e46185-dd8a-43af-beb8-b9b9b082250f.png)

**Comment by yang7857854** [comment]
Hi, 

Since F2A will call the dll located in the win64 folder and write a temp file, Thus, I think you need to change the authority permission of the folder. Sometimes the files in sub-folders of Program Files cannot be modified as set by default. You need to enable the authority to write, read, change, remove, etc,  for the aqwa/bin/win64 folder. 

Kind regards,

Yang

**Comment by ashwing1407** [comment]
Hello Yang,
Thank You for quick response.
I have another problem, simulation is running fine now, but after extracting the results as defined in the F2A user manual and it is saved in the individual folder. But the obtained .dat files are empty  as shown in attached image. 
![Screenshot 2022-10-21 102349](https://user-images.githubusercontent.com/85031933/197115259-eeb8b17b-a011-4b36-9a73-428c1ff683b2.png)
 Can you explain why?

**Comment by ashwing1407** [comment]
Hello Yang,
Thanks for early reply. I am able to run F2A code as mentioned in the user manual. Now, I want to use the .fst file which is generated from OpenFast. It is showing error as shown below, this error may be due to change in version. Can you explain me how to use the file which is generated from OpenFast as I am new to this.

Thanks and Regards 
 ![echo](https://user-images.githubusercontent.com/85031933/197233976-c487b38b-eb5e-4a2e-b0c1-888e7fc0cdb6.png)

**Comment by yang7857854** [comment]
Hi,

This error is caused by the wrong format of the .fst file. Please compare TAQWA.fst with the fst file provided in the example folder, and make sure that every variable in your fst file is in the same line with the example.

**Comment by yang7857854** [comment]
Hi,

I think you need to modify the input of rhe aqwa result extraction file to make it compatible with your case.

There is another reason to this error. Maybe you are using a later version of AQWA that generates a different structured data file.



| |
Yang Yang
Ningbo University  - 
Associate Professor
+86-0574-87604348
***@***.***
169 South Qixing Road, Ningbo
Postcode: 315832
Web: hyxy.nbu.edu.cn/info/1178/10531.htm
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 10/21/2022 12:56 |
| To | ***@***.***> |
| Cc | Yang ***@***.******@***.***> |
| Subject | Re: [yang7857854/F2A] Issue- forrtl: severe (9): permission to access file denied, unit 11, file C:\Program Files\ANSYS Inc\v211\aqwa\bin\winx64\PMESSAGE.TMP (Issue #2) |

Hello Yang,
Thank You for quick response.
I have another problem, simulation is running fine now, but after extracting the results as defined in the F2A user manual and it is saved in the individual folder. But the obtained .dat files are empty as shown in attached image.

Can you explain why?

**Comment by ashwing1407** [comment]
Hello Yang,
I am trying to rebuild the master code (user_force.f90)  using the all source code available in F2A folder in Visual Studio 2019+ intel fortran compiler.  user_force64.dll  file is generated as usual but by initializing AQWA  through cmd shows the following error.
It works fine while using dll file provided by you in the F2A folder.
![image](https://user-images.githubusercontent.com/85031933/210240467-d4b482e8-3cbb-4f32-aa72-b91f1a7f671d.png)
![Screenshot 2023-01-02 192304](https://user-images.githubusercontent.com/85031933/210240522-8d6c1e84-9e51-4e9f-b4e3-0832406d2356.png)
 
Please guide me through it.
Thank You

**Comment by yang7857854** [comment]
Hi,


When you try to run F2A through the cmd window, you need to specify the path of the AQWA input (.dat). 


FAST (FAST_IO.f90) has called a subroutine (checkArgs) to identify the input from the CMD window. Please ensure this line is commented out as below.


Kind regards,


Yang




| |
Yang Yang
Ningbo University  - 
Associate Professor
+86-0574-87604348
***@***.***
169 South Qixing Road, Ningbo
Postcode: 315832
Web: hyxy.nbu.edu.cn/info/1178/10531.htm
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 1/2/2023 21:58 |
| To | ***@***.***> |
| Cc | Yang ***@***.***> ,
***@***.***> |
| Subject | Re: [yang7857854/F2A] Issue- forrtl: severe (9): permission to access file denied, unit 11, file C:\Program Files\ANSYS Inc\v211\aqwa\bin\winx64\PMESSAGE.TMP (Issue #2) |

Hello Yang,
I am trying to rebuild the master code (user_force.f90) using the all source code available in F2A folder in Visual Studio 2019+ intel fortran compiler. user_force64.dll file is generated as usual but by initializing AQWA through cmd shows the following error.
It works fine while using dll file provided by you in the F2A folder.



Please guide me through it.
Thank You

**Comment by ashwing1407** [comment]
Hello Sir, 
I already commented out that line in (FAST_IO.f90) in previous trials but it is still showing the same error.
![c](https://user-images.githubusercontent.com/85031933/210323485-f90f8a33-fd74-458f-a01c-4cb9c182338c.png)

**Comment by yang7857854** [comment]
Hi,


Please try to specify the directory of and filename of the AQWA input (.dat). If this does not help either, then I suspect it is the problem of the OS and I can't suggest more.


Kind regards,


Yang


| |
Yang Yang
Ningbo University  - 
Associate Professor
+86-0574-87604348
***@***.***
169 South Qixing Road, Ningbo
Postcode: 315832
Web: hyxy.nbu.edu.cn/info/1178/10531.htm
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 1/3/2023 16:42 |
| To | ***@***.***> |
| Cc | Yang ***@***.***> ,
***@***.***> |
| Subject | Re: [yang7857854/F2A] Issue- forrtl: severe (9): permission to access file denied, unit 11, file C:\Program Files\ANSYS Inc\v211\aqwa\bin\winx64\PMESSAGE.TMP (Issue #2) |

Hello Sir,
I already commented out that line in (FAST_IO.f90) in previous trials but it is still showing the same error.

**Comment by ashwing1407** [comment]
Hii,
The above problem is due to the different versions of the compiler used. May I please know how you build the dll file or which compiler(version) you used?

Thank You

**Comment by yang7857854** [comment]
Hi,


The DLL was compiled using VS2013 and Intel fortran 2010.


| |
Yang Yang
Ningbo University  - 
Associate Professor
+86-0574-87604348
***@***.***
169 South Qixing Road, Ningbo
Postcode: 315832
Web: hyxy.nbu.edu.cn/info/1178/10531.htm
|
签名由网易邮箱大师定制
On 1/3/2023 17:10，YANG Yang/杨 ***@***.***> wrote：
Hi,


Please try to specify the directory of and filename of the AQWA input (.dat). If this does not help either, then I suspect it is the problem of the OS and I can't suggest more.


Kind regards,


Yang


| |
Yang Yang
Ningbo University  - 
Associate Professor
+86-0574-87604348
***@***.***
169 South Qixing Road, Ningbo
Postcode: 315832
Web: hyxy.nbu.edu.cn/info/1178/10531.htm
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 1/3/2023 16:42 |
| To | ***@***.***> |
| Cc | Yang ***@***.***> ,
***@***.***> |
| Subject | Re: [yang7857854/F2A] Issue- forrtl: severe (9): permission to access file denied, unit 11, file C:\Program Files\ANSYS Inc\v211\aqwa\bin\winx64\PMESSAGE.TMP (Issue #2) |

Hello Sir,
I already commented out that line in (FAST_IO.f90) in previous trials but it is still showing the same error.
